### ISSUE TITLE
run install have a err

### ISSUE THREAD

**Issue by ruanlianjun** [bitnami/bitnami-docker-etcd#31] opened 2021-12-22 06:38 UTC
[38;5;6metcd [38;5;5m06:35:11.81 [0m[38;5;1mERROR[0m ==> Unhealthy endpoint!                                                                               ││   Warning  Unhealthy  2m49s  kubelet  Readiness probe failed: {"level":"warn","ts":1640154921.8267612,"logger":"client","caller":"v3/retry_interceptor.go: ││ 62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00031ea80/helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379"," ││ attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error wh ││ ile dialing dial tcp 100.96.205.200:2379: connect: connection refused\""}                                                                                  ││ helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded                      ││ Error: unhealthy cluster                                                                                                                                   ││ [38;5;6metcd [38;5;5m06:35:21.82 [0m[38;5;1mERROR[0m ==> Unhealthy endpoint!                                                                               ││   Warning  Unhealthy  2m41s  kubelet  Liveness probe failed: {"level":"warn","ts":1640154929.8793547,"logger":"client","caller":"v3/retry_interceptor.go:6 ││ 2","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00044e380/helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379","a ││ ttempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error whi ││ le dialing dial tcp 100.96.205.200:2379: connect: connection refused\""}                                                                                   ││ helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded                      ││ Error: unhealthy cluster                                                                                                                                   ││ [38;5;6metcd [38;5;5m06:35:29.88 [0m[38;5;1mERROR[0m ==> Unhealthy endpoint!                                                                               ││   Warning  Unhealthy  2m39s  kubelet  Readiness probe failed: {"level":"warn","ts":1640154931.894572,"logger":"client","caller":"v3/retry_interceptor.go:6 ││ 2","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000362700/helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379","a ││ ttempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error whi ││ le dialing dial tcp 100.96.205.200:2379: connect: connection refused\""}                                                                                   ││ helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded                      ││ Error: unhealthy cluster                                                                                                                                   ││ [38;5;6metcd [38;5;5m06:35:31.89 [0m[38;5;1mERROR[0m ==> Unhealthy endpoint!                                                                               ││   Warning  Unhealthy  2m29s  kubelet  Readiness probe failed: {"level":"warn","ts":1640154941.7804928,"logger":"client","caller":"v3/retry_interceptor.go: ││ 62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00031ca80/helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379"," ││ attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error wh ││ ile dialing dial tcp 100.96.205.200:2379: connect: connection refused\""}                                                                                  ││ helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded                      ││ Error: unhealthy cluster                                                                                                                                   ││ [38;5;6metcd [38;5;5m06:35:41.78 [0m[38;5;1mERROR[0m ==> Unhealthy endpoint!                                                                               ││   Normal   Started    116s (x2 over 4m34s)  kubelet  Started container etcd                                                                                ││   Normal   Created    116s (x2 over 4m35s)  kubelet  Created container etcd                                                                                │
│   Warning  Unhealthy  29s (x8 over 2m19s)   kubelet  (combined from similar events): Readiness probe failed: {"level":"warn","ts":1640155061.7676415,"logg │
│ er":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000362a80/helm-etcd-new-0.helm-e │
│ tcd-new-headless.helm.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: │
│  connection error: desc = \"transport: Error while dialing dial tcp 100.96.205.200:2379: connect: connection refused\""}                                   │
│ helm-etcd-new-0.helm-etcd-new-headless.helm.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded                      │
│ Error: unhealthy cluster                                                                                                                                   │
│ [38;5;6metcd [38;5;5m06:37:41.77 [0m[38;5;1mERROR[0m ==> Unhealthy endpoint!                                                                               │
│   Warning  BackOff  27s                  kubelet  Back-off restarting failed container                                                                     │
│   Normal   Pulled   16s (x3 over 4m35s)  kubelet  Container image "docker.io/bitnami/etcd:3.5.1-debian-10-r56" already present on machine                  │
│

**Comment by javsalgar** [comment] 2021-12-22 09:57
Looks like a duplicate of https://github.com/bitnami/bitnami-docker-etcd/issues/30, closing

**Closed by javsalgar** 2021-12-22 09:57 UTC
